// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["https://console.prisma.io/fh3z01cu4v1xxycw3vetpn55/cmjjv3blh0gybyxe9fj71rh1u/cmjjv3blh0gy7yxe9yqezqnj3"],
  },
});
